export const consoles = {
  PSP: "primary",
  "Playstation 1": "primary",
  "Playstation 2": "primary",
  "Playstation 3": "primary",
  "Playstation 4": "primary",
  "Playstation 5": "primary",
  Xbox: "success",
  "Xbox 360": "success",
  "Xbox One": "success",
  "Xbox Series X": "success",
  "Nintendo 64": "warning",
  "Nintendo Gamecube": "warning",
  "Nintendo Wii": "warning",
  "Nintendo Wii U": "warning",
  "Nintendo Switch": "warning",
  "Microsoft Windows": "danger",
  Steam: "danger",
};
